name: Laravel Tests

on:
  push:
    branches:
      - main  # Voer de actie uit bij een push naar main
  pull_request:
    branches:
      - main  # Voer ook tests uit bij pull requests naar main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer PHP en extensies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2  # Pas aan naar jouw PHP-versie
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Installeer Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Kopieer .env bestand
        run: cp .env.example .env

      - name: Genereer application key
        run: php artisan key:generate

      - name: Wacht tot MySQL gereed is
        run: sleep 10s

      - name: Voer database migraties uit
        run: php artisan migrate --env=testing --force

      - name: Voer de tests uit
        run: php artisan test
